// Generated by @wagmi/cli@0.1.15 on 7/6/2023 at 3:52:58 PM

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// TVLStaking
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const tvlStakingABI = [
  {
    stateMutability: 'nonpayable',
    type: 'constructor',
    inputs: [
      {
        name: 'tokenForEarnings_',
        internalType: 'contract IERC20',
        type: 'address',
      },
      {
        name: 'treasury_',
        internalType: 'contract ITreasuryWithNFT',
        type: 'address',
      },
      { name: 'vault_', internalType: 'address', type: 'address' },
      {
        name: 'registry_',
        internalType: 'contract IRegistry',
        type: 'address',
      },
      {
        name: 'economicModuleHub_',
        internalType: 'contract IEconomicModuleHub',
        type: 'address',
      },
      { name: 'dapp', internalType: 'address', type: 'address' },
      {
        name: 'metaIdentityStaking_',
        internalType: 'contract MetaIdentityStaking',
        type: 'address',
      },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'economic',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'Deposit',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'economic',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'EmergencyUnstake',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'previousOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'OwnershipTransferred',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'economic',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'Unstake',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'point',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'pointCurrent',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'UpdateStake',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'economic',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'payee',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'passFeeRecipient',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'developer',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'WithdrawReward',
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'TVLCurrency',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: '_dapp',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'economicModuleHub',
    outputs: [
      {
        name: '',
        internalType: 'contract IEconomicModuleHub',
        type: 'address',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'economic', internalType: 'address', type: 'address' }],
    name: 'emergencyUnstake',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'endBlock',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'pure',
    type: 'function',
    inputs: [
      { name: '_from', internalType: 'uint256', type: 'uint256' },
      { name: '_to', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'getMultiplier',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'economic', internalType: 'address', type: 'address' }],
    name: 'getPoints',
    outputs: [{ name: 'tvl', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'metaIdentityStaking',
    outputs: [
      {
        name: '',
        internalType: 'contract MetaIdentityStaking',
        type: 'address',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'economic', internalType: 'address', type: 'address' }],
    name: 'pendingToken',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'poolInfo',
    outputs: [
      { name: 'pointsSupply', internalType: 'uint256', type: 'uint256' },
      { name: 'lastRewardBlock', internalType: 'uint256', type: 'uint256' },
      { name: 'accTokenPerShare', internalType: 'uint256', type: 'uint256' },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '', internalType: 'uint96', type: 'uint96' }],
    name: 'refresh',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'registry',
    outputs: [
      { name: '', internalType: 'contract IRegistry', type: 'address' },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'economic', internalType: 'address', type: 'address' }],
    name: 'stake',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'economic', internalType: 'address', type: 'address' }],
    name: 'subStaking',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'tokenForEarnings',
    outputs: [{ name: '', internalType: 'contract IERC20', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'tokenPerBlock',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'unpaidTokens',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'economic', internalType: 'address', type: 'address' }],
    name: 'unstake',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'updatePool',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'updateReward',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'userInfo',
    outputs: [
      { name: 'points', internalType: 'uint256', type: 'uint256' },
      { name: 'rewardDebt', internalType: 'uint256', type: 'uint256' },
      { name: 'payee', internalType: 'address', type: 'address' },
      { name: 'passFeeRecipient', internalType: 'address', type: 'address' },
      { name: 'developer', internalType: 'address', type: 'address' },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'vault',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'economic', internalType: 'address', type: 'address' }],
    name: 'withdrawReward',
    outputs: [{ name: 'pending', internalType: 'uint256', type: 'uint256' }],
  },
] as const
